# GitLeaks configuration for CatNet project
title = "CatNet GitLeaks Config"

# Extend default configuration
[extend]
useDefault = true

# Allowlist configuration
[allowlist]
description = "Allowlist for CatNet project"
paths = [
    "docs/.*\\.md",
    "README\\.md",
    "IMPLEMENTATION_PLAN\\.md",
    "CLAUDE\\.md"
]

# Allow specific patterns
regexes = [
    "YOUR_API_KEY_HERE",
    "your-api-key",
    "your-.*-token",
    "example\\.com",
    "test@example\\.com"
]