[allowlist]
description = "Allowlist for CatNet project"

[[allowlist.regexes]]
description = "Allow placeholder API keys in documentation"
regex = '''YOUR_API_KEY_HERE'''

[[allowlist.regexes]]
description = "Allow example tokens in documentation"
regex = '''your-api-key'''

[[allowlist.regexes]]
description = "Allow example secrets in documentation"
regex = '''your-.*-token'''

[[allowlist.paths]]
description = "Allow all documentation files"
paths = [
    '''docs/.*\.md''',
    '''README\.md''',
    '''IMPLEMENTATION_PLAN\.md''',
]

# Extend default configuration
[extend]
useDefault = true