# CatNet Prometheus Configuration
# Following CLAUDE.md monitoring requirements

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'catnet-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - '/etc/prometheus/alerts.yml'

# Scrape configurations
scrape_configs:
  # CatNet Services
  - job_name: 'catnet-auth'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'catnet-gitops'
    static_configs:
      - targets: ['gitops-service:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'catnet-deployment'
    static_configs:
      - targets: ['deployment-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'catnet-device'
    static_configs:
      - targets: ['device-service:8084']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Database monitoring
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:9187']

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']